export const DOG_BREEDS = [
  "Labrador Retriever",
  "Golden Retriever",
  "Bulldog Francês",
  "Pastor Alemão",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "Yorkshire Terrier",
  "Shih Tzu",
  "Dachshund",
  "Border Collie",
  "Husky Siberiano",
  "Boxer",
  "Cocker Spaniel",
  "Doberman",
  "Lhasa Apso",
  "Maltese",
  "Pinscher Miniatura",
  "Spitz Alemão",
  "Bichon Frisé",
  "Akita",
  "Chow Chow",
  "Dálmata",
  "Samoieda",
  "Weimaraner",
  "Basset Hound",
  "Bull Terrier",
  "Chihuahua",
  "Pug",
  "Sem Raça Definida (SRD)",
] as const;

export type DogBreed = (typeof DOG_BREEDS)[number];
